- name: Debug Distribution Facts
  hosts: "all"
  gather_subset:
    - distribution
    - os_family
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
