- name: Testing Nested Loops
  hosts: all
  tasks:
    - name: Creating VLAN
      debug:
        msg: "Creating VLAN {{ item.id }}..."
      loop: "{{ vlans }}"
    - name: Adding ports to VLAN
      debug:
        msg: "Adding port {{ item.1.port }} for vlan {{ item.0.name }}..."
      loop: "{{ vlans | subelements('ports') }}"
