- name: Post Provision Configurations
  hosts: "all"
  gather_facts: no
  tasks:
    - name: Add default user with sudo privileges
      ansible.builtin.user:
        name: "{{ default_user }}"
        group: wheel

    - name: Allow passwordless sudo for default user
      ansible.builtin.copy:
        content: "{{ default_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/{{ default_user }}_nopasswd
        mode: 0600
        validate: /usr/sbin/visudo -csf %s

    - name: Add authorized key to default user
      ansible.posix.authorized_key:
        user: "{{ default_user }}"
        state: present
        key: "{{ public_key }}"

    - name: Disable root ssh
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        backup: yes

    - name: Reload sshd service
      ansible.builtin.systemd_service:
        name: sshd
        state: reloaded
