switch:
  hosts:
    192.168.22.60:
      ansible_network_os: cisco.nxos.nxos
      ansible_host_key_checking: false
      ansible_user: admin
      ansible_password: Admin123!
  vars:
    ansible_connection: ansible.netcommon.network_cli
